name: SSH to Server

on:
  push:
    branches:
      - main

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: print out example job
        uses: appleboy/ssh-action@v.0.1.3
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: | 
            echo "Nice Job!!!"
