name: SSH to Server

on:
  push:
    branches:
      - main

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
    - name: install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_ADDRESS }} > ~/.ssh/known_hosts
    - name: connect
      run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_ADDRESS }} echo " Hello World !"
